SoilServer/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from Users.views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^bind/', include('bind.urls')),
    url(r'^users/', include('Users.urls')),
    url(r'^assets/', include('assets.urls')),
    url(r'^faults/', include('faults.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
]

bind/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/', views.DomainAdd, name='domain_add'),
    url(r'^list/', views.DomainList, name='domain_list'),
    url(r'^delete/', views.DomainDel, name='domain_delete'),
    url(r'^update/', views.DomainUpdate, name='domain_update'),
    url(r'^profile/', views.DomainProfile, name='domain_profile'),
]

faults/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from . import views

urlpatterns = [
    # Faults URL
    url(r'^add/', views.FaultsAdd, name='faults_add'),
    url(r'^list/', views.FaultsList, name='faults_list'),
    url(r'^delete/', views.FaultsDel, name='faults_delete'),
    url(r'^update/', views.FaultsUpdate, name='faults_update'),
    url(r'^details/', views.FaultsDetails, name='faults_details'),
    url(r'^profile/', views.FaultsProfile, name='faults_profile'),
    # Fault Seleted
    url(r'^level_seleted/', views.SeletedLevel, name='level_seleted'),
    url(r'^class_seleted/', views.SeletedClass, name='class_seleted'),
    url(r'^status_seleted', views.SeletedStatus, name='status_seleted'),
    url(r'^project_seleted/', views.SeletedProject, name='project_seleted'),
    url(r'^improve_seleted/', views.SeletedImprove, name='improve_seleted'),
]

faults/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser, User, Group


# Create your models here.
class FaultsClass(models.Model):
    name = models.CharField(max_length=255, verbose_name=u"故障分类")

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'faults_class'


class FaultsProject(models.Model):
    name = models.CharField(max_length=255, verbose_name=u"故障项目")

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'faults_project'


class FaultsContent(models.Model):
    fault_level_choices = (
        (0, u"P0"),
        (1, u"P1"),
        (2, u"P2"),
        (3, u"P3"),
        (4, u"P4"),
    )

    fault_status_choices = (
        (0, u"处理中"),
        (1, u"改进中"),
        (2, u"已恢复"),
        (3, u"已完结"),
    )

    fault_improve_choices = (
        (0, u"开发"),
        (1, u"运维"),
        (2, u"机房"),
        (3, u"网络"),
        (4, u"其他"),
    )

    name = models.CharField(u'故障名称', max_length=255, blank=False, null=False, unique=True)
    level = models.IntegerField(u'故障级别', choices=fault_level_choices)
    type = models.ForeignKey(u'FaultsClass', verbose_name=u'故障类型')
    effect = models.TextField(u'故障影响', blank=True, null=True)
    reasons = models.TextField(u'故障原因', blank=True, null=True)
    solution = models.TextField(u'解决方案', blank=True, null=True)
    content = models.TextField(u'处理流程', blank=True, null=True)
    project = models.ForeignKey(u'FaultsProject', verbose_name=u'影响项目')
    status = models.IntegerField(u'故障状态', choices=fault_status_choices)
    improve = models.IntegerField(u'主导改进', choices=fault_improve_choices)
    lesson = models.TextField(blank=True, verbose_name=u'经验总结')
    start_time = models.DateTimeField(u'开始时间')
    end_time = models.DateTimeField(u'结束时间')
    create_datetime = models.DateTimeField(u'创建时间', auto_now=True)
    update_datetime = models.DateTimeField(u'更新时间', auto_now_add=True)

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = u'faults_content'

faults/forms.py
# -*- coding: UTF-8 -*-

from models import *
from django import forms

class FaultsValidForm(forms.Form):
    id = forms.IntegerField(required=False)
    name = forms.CharField(required=False)
    level = forms.IntegerField(required=False)
    type = forms.CharField(required=False)
    effect = forms.CharField(widget=forms.Textarea, required=False)
    reasons = forms.CharField(widget=forms.Textarea, required=False)
    solution = forms.CharField(widget=forms.Textarea, required=False)
    content = forms.CharField(widget=forms.Textarea, required=False)
    lesson = forms.CharField(widget=forms.Textarea, required=False)
    project = forms.IntegerField(required=False)
    status = forms.IntegerField(required=False)
    improve = forms.IntegerField(required=False)
    start_time = forms.DateTimeField(required=False)
    end_time = forms.DateTimeField(required=False)


class FaultsDelValidForm(forms.Form):
    id = forms.IntegerField(required=False)

    def clean_id(self):
        id = self.cleaned_data['id']
        if FaultsContent.objects.filter(id=id).exists():
            return id
        else:
            raise forms.ValidationError('当前故障简述编号不存在，请选择的故障简述编号.')

faults/views.py
# -*- coding: utf-8 -*-

import json
import time
from models import *
from forms import *
import django.utils.timezone as timezone
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

'''统计时间'''
def CountTime(result, start_time, end_time):
    start_time = time.strptime(str(start_time).split('+')[0], "%Y-%m-%d %H:%M:%S")
    end_time = time.strptime(str(end_time).split('+')[0], "%Y-%m-%d %H:%M:%S")
    timestamp = int(time.mktime(end_time)) - int(time.mktime(start_time))

    setattr(result, 'time', str(timestamp // 3600) + '小时' + str(timestamp % 3600 // 60) + '分')

'''故障列表'''
@csrf_exempt
@login_required(login_url="/users/login/")
def FaultsList(request):
    result = FaultsContent.objects.select_related().all()
    for fault in result:
        CountTime(fault, fault.start_time, fault.end_time)
    return render(request, 'faults/list.html', {'result': result})


'''故障添加'''
@csrf_exempt
@login_required(login_url="/users/login/")
def FaultsAdd(request):
    if request.method == 'GET':
        return render(request, 'faults/add.html')
    elif request.method == 'POST':
        fault_form = FaultsValidForm(request.POST)
        if fault_form.is_valid():
            # 项目概述
            name = fault_form.cleaned_data['name']
            # 项目级别
            level = fault_form.cleaned_data['level']
            # 项目类型
            type = fault_form.cleaned_data['type']
            # 影响项目
            project = fault_form.cleaned_data['project']
            # 故障状态
            status = fault_form.cleaned_data['status']
            # 主导改进
            improve = fault_form.cleaned_data['improve']
            # 开始时间
            start_time = fault_form.cleaned_data['start_time']
            # 结束时间
            end_time = fault_form.cleaned_data['end_time']
            # 故障影响
            effect = fault_form.cleaned_data['effect']
            # 处理流程
            content = fault_form.cleaned_data['content']
            # 故障原因
            reasons = fault_form.cleaned_data['reasons']
            # 解决方案
            solution = fault_form.cleaned_data['solution']
            # 经验总结
            lesson = fault_form.cleaned_data['lesson']

            # 获取项目类型
            Type_name = FaultsClass.objects.filter(id=type).values('name')
            Type = FaultsClass.objects.get(name=Type_name)

            # 获取项目名称
            project_name = FaultsProject.objects.filter(id=project).values('name')
            project = FaultsProject.objects.get(name=project_name)

            # 添加数据
            AddObj = FaultsContent(name=name,
                                   level=level,
                                   type=Type,
                                   project=project,
                                   status=status,
                                   improve=improve,
                                   effect=effect,
                                   content=content,
                                   reasons=reasons,
                                   solution=solution,
                                   lesson=lesson,
                                   start_time=start_time,
                                   end_time=end_time)
            AddObj.save()

            # 数据添加状态: true表示正常.
            return HttpResponse(json.dumps({'status': 'true'}))
        else:
            # 数据添加状态: false表示异常.
            return HttpResponse(json.dumps({'status': 'false'}))
    else:
        fault_form = FaultsValidForm()


'''故障更新'''
@csrf_exempt
@login_required(login_url="/users/login/")
def FaultsUpdate(request):
    if request.method == 'POST':
        fault_upform = FaultsValidForm(request.POST)
        print fault_upform
        if fault_upform.is_valid():
            id = fault_upform.cleaned_data['id']
            # 项目概述
            name = fault_upform.cleaned_data['name']
            # 项目级别
            level = fault_upform.cleaned_data['level']
            # 项目类型
            type = fault_upform.cleaned_data['type']
            # 影响项目
            project = fault_upform.cleaned_data['project']
            # 故障状态
            status = fault_upform.cleaned_data['status']
            # 主导改进
            improve = fault_upform.cleaned_data['improve']
            # 开始时间
            start_time = fault_upform.cleaned_data['start_time']
            # 结束时间
            end_time = fault_upform.cleaned_data['end_time']
            # 故障影响
            effect = fault_upform.cleaned_data['effect']
            # 处理流程
            content = fault_upform.cleaned_data['content']
            # 故障原因
            reasons = fault_upform.cleaned_data['reasons']
            # 解决方案
            solution = fault_upform.cleaned_data['solution']
            # 经验总结
            lesson = fault_upform.cleaned_data['lesson']

            # 获取项目类型
            Type_name = FaultsClass.objects.filter(id=type).values('name')
            Type = FaultsClass.objects.get(name=Type_name)

            # 获取项目名称
            project_name = FaultsProject.objects.filter(id=project).values('name')
            project = FaultsProject.objects.get(name=project_name)

            # 更新数据
            AddObj = FaultsContent.objects.filter(id=id).update(name=name,
                                                                level=level,
                                                                type=Type,
                                                                project=project,
                                                                status=status,
                                                                improve=improve,
                                                                effect=effect,
                                                                content=content,
                                                                reasons=reasons,
                                                                solution=solution,
                                                                lesson=lesson,
                                                                start_time=start_time,
                                                                end_time=end_time)

            # 数据添加状态: true表示正常.
            return HttpResponse(json.dumps({'status': 'true'}))
        else:
            # 数据添加状态: false表示异常.
            return HttpResponse(json.dumps({'status': 'false'}))
    else:
        fault_upform = FaultsValidForm()

'''故障删除'''
@csrf_exempt
@login_required(login_url="/users/login/")
def FaultsDel(request):
    if request.method == 'POST':
        fault_delform = FaultsDelValidForm(request.POST)
        if fault_delform.is_valid():
            id = fault_delform.cleaned_data['id']
            DelObj = FaultsContent.objects.filter(id=id).delete()
            # 数据删除状态: true表示正常.
            return HttpResponse(json.dumps({'status': 'true'}))
        else:
            # 数据删除状态: false表示异常.
            return HttpResponse(json.dumps({'status': 'false'}))
    else:
        idc_delform = FaultsDelValidForm()

'''故障编辑'''
@csrf_exempt
@login_required(login_url="/users/login/")
def FaultsProfile(request):
    if request.method == 'GET':
        id = request.GET['id']
        result = FaultsContent.objects.filter(id=id)
    return render(request, 'faults/profile.html', {'result': result})

'''故障详情'''
@csrf_exempt
@login_required(login_url="/users/login/")
def FaultsDetails(request):
    if request.method == 'GET':
        id = request.GET['id']
    result = FaultsContent.objects.filter(id=id)
    return render(request, 'faults/details.html', {'result': result})

'''故障级别列表'''
def SeletedLevel(request):
    if request.method == 'GET':
        result = FaultsContent.fault_level_choices
        return HttpResponse(json.dumps(list(result)))

'''项目类型列表'''
def SeletedClass(request):
    if request.method == 'GET':
        result = FaultsClass.objects.all().values('id', 'name')
        return HttpResponse(json.dumps(list(result)))

'''项目名称列表'''
def SeletedProject(request):
    if request.method == 'GET':
        result = FaultsProject.objects.all().values('id', 'name')
        return HttpResponse(json.dumps(list(result)))

'''故障状态列表'''
def SeletedStatus(request):
    if request.method == 'GET':
        result = FaultsContent.fault_status_choices
        return HttpResponse(json.dumps(list(result)))

'''主导改进列表'''
def SeletedImprove(request):
    if request.method == 'GET':
        result = FaultsContent.fault_improve_choices
        return HttpResponse(json.dumps(list(result)))

templates/faults/list.html
{% extends "base_site.html" %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/css/dataTables.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>故障管理</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>故障列表</h2>
              <ul class="nav navbar-right panel_toolbox">
			    <li><a class="collapse-link" href="{% url 'faults_add' %}"><i class="glyphicon glyphicon-plus"></i></a>
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table id="CustomDatatable" class="table table-striped table-bordered">
                <thead>
                  <tr>
                    <th>故障名称</th>
                    <th>故障级别</th>
                    <th>故障类型</th>
                    <th>影响业务</th>
                    <th>主导改进</th>
                    <th>持续时间</th>
                    <th>故障状态</th>
                    <th>创建时间</th>
                    <th>操作</th>
                  </tr>
                </thead>
                <tbody>
                  {% for fault in result %}
                  <tr>
                    <td>{{ fault.name }}</td>
                    <td>{{ fault.get_level_display }}</td>
                    <td>{{ fault.type }}</td>
                    <td>{{ fault.project }}</td>
                    <td>{{ fault.get_improve_display }}</td>
                    <td>{{ fault.time }}</td>
                    {% if fault.status == 0 %}
                      <td class="text-danger">{{ fault.get_status_display }}</td>
                    {% elif fault.status == 1 %}
                      <td class="text-warning">{{ fault.get_status_display }}</td>
                    {% elif fault.status == 2 %}
                      <td class="text-primary">{{ fault.get_status_display }}</td>
                    {% elif fault.status == 3 %}
                      <td class="text-success">{{ fault.get_status_display }}</td>
                    {% endif %}
                    <td>{{ fault.create_datetime }}</td>
                    <td>
                      <a class="btn btn-success btn-xs" href="{% url 'faults_details' %}?id={{ fault.id }}">详情</a>
                      <a class="btn btn-info btn-xs" href="{% url 'faults_profile' %}?id={{ fault.id }}">编辑</a>
                      <span class="del_fault" CurlId="{{ fault.id }}">
                        <button type="button" class="btn btn-danger btn-xs">删除</button>
                      </span>
                    </td>
                  </tr>
                  {% endfor %}
              </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- 自定义js -->
  <script src="/static/js/validfaultsform.init.js"></script>
{% endblock javascripts %}

templates/faults/profile.html
{% extends "base_site.html" %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/css/bootstrap-select.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>故障管理</h3>
        </div>
        <div class="title_right"></div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>添加故障</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <br />
              <form id="up_faultForm" data-parsley-validate class="form-horizontal form-label-left" action="{% url 'faults_profile' %}" method="post" role="search">
                {% csrf_token %}
                {% for fault in result %}
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">故障概述 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="hidden" id="get_id" name="get_id" class="form-control col-md-7 col-xs-12"  value="{{ fault.id }}">
                    <input type="text" id="name" name="name" class="form-control col-md-7 col-xs-12"  value="{{ fault.name }}">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for=level">故障级别 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <!-- 故障级别 -->
                    <input type="hidden" id="get_level" name="get_level" class="form-control col-md-7 col-xs-12"  value="{{ fault.get_level_display }}">
                    <select class="form-control" id="level" name="level">
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for=type">故障类型 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <!-- 故障类型 -->
                    <input type="hidden" id="get_type" name="get_type" class="form-control col-md-7 col-xs-12"  value="{{ fault.type }}">
                    <select class="form-control" id="type" name="type">
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="project">影响项目 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <!-- 影响项目 -->
                    <input type="hidden" id="get_project" name="get_project" class="form-control col-md-7 col-xs-12"  value="{{ fault.project }}">
                    <select class="form-control" id="project" name="project">
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="status">故障状态 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <!-- 故障状态 -->
                    <input type="hidden" id="get_status" name="get_status" class="form-control col-md-7 col-xs-12"  value="{{ fault.get_status_display }}">
                    <select class="form-control" id="status" name="status">
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="improve">主导改进 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <!-- 主导改进 -->
                    <input type="hidden" id="get_improve" name="get_improve" class="form-control col-md-7 col-xs-12"  value="{{ fault.get_improve_display }}">
                    <select class="form-control" id="improve" name="improve">
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="duration_time">持续时间 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="hidden" id="starttime" name="starttime" class="form-control col-md-7 col-xs-12" value="{{ fault.start_time }}">
                    <input type="hidden" id="endtime" name="duration_time" class="form-control col-md-7 col-xs-12" value="{{ fault.end_time }}">
                    <input type="text" id="duration_time" name="duration_time" class="form-control col-md-7 col-xs-12">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="effect">故障影响 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="effect" class="form-control" name="effect" data-parsley-trigger="keyup" data-parsley-minlength="20"
                              data-parsley-maxlength="40"
                              data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.."
                              data-parsley-validation-threshold="20">{{ fault.effect }}</textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="content">处理流程 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="content" class="form-control" name="content" data-parsley-trigger="keyup" data-parsley-minlength="20"
                              data-parsley-maxlength="200"
                              data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.."
                              data-parsley-validation-threshold="20">{{ fault.content }}</textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="reasons">故障原因 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="reasons" class="form-control" name="reasons" data-parsley-trigger="keyup" data-parsley-minlength="20"
                              data-parsley-maxlength="200"
                              data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.."
                              data-parsley-validation-threshold="20">{{ fault.reasons }}</textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="solution">解决方案 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="solution" class="form-control" name="solution" data-parsley-trigger="keyup" data-parsley-minlength="20"
                              data-parsley-maxlength="200"
                              data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.."
                              data-parsley-validation-threshold="20">{{ fault.solution }}</textarea>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="lesson">经验总结 <span class="required"> </span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <textarea id="lesson" class="form-control" name="lesson" data-parsley-trigger="keyup" data-parsley-minlength="20"
                              data-parsley-maxlength="100"
                              data-parsley-minlength-message="Come on! You need to enter at least a 20 caracters long comment.."
                              data-parsley-validation-threshold="10">{{ fault.lesson }}</textarea>
                  </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <span class="up_faultValid" CurlId="{{ fault.id }}">
                      <button type="button" class="btn btn-success">保存</button>
                    </span>
                    <span class="up_faultReset">
                      <button class="btn btn-primary" type="reset">重置</button>
                    </span>
                  </div>
                </div>
              </form>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- 自定义js -->
  <script src="/static/js/validfaultsform.init.js"></script>
{% endblock javascripts %}