SoilServer/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.contrib import admin
from Users.views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^bind/', include('bind.urls')),
    url(r'^users/', include('Users.urls')),
    url(r'^assets/', include('assets.urls')),
    url(r'^faults/', include('faults.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
]

bind/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add/', views.DomainAdd, name='domain_add'),
    url(r'^list/', views.DomainList, name='domain_list'),
    url(r'^delete/', views.DomainDel, name='domain_delete'),
    url(r'^update/', views.DomainUpdate, name='domain_update'),
    url(r'^profile/', views.DomainProfile, name='domain_profile'),
]

bind/models.py
# -*- coding: utf-8 -*-

from django.db import models
import django.utils.timezone as timezone

class DNS(models.Model):
    dns_type_choice = (
        ('A', 'A- 将域名指向一个IPV4地址'),
        ('CNAME', 'CNAME- 将域名指向另外一个域名'),
        ('AAAA', 'AAAA- 将域名指向一个IPV6地址'),
    )

    dns_zone_choice = (
        (0, 'linux-testing.com'),
    )

    zone = models.IntegerField(u'Zone', choices=dns_zone_choice, default=0)
    host = models.CharField(u'记录名称', max_length=128, blank=False, null=False)
    type = models.CharField(u'记录类型', max_length=128, choices=dns_type_choice, default='A')
    data = models.CharField(u'记录值', max_length=128, blank=False, null=False)
    ttl = models.IntegerField(u'TTL时间', blank=False,null=False)
    mx_priority = models.IntegerField(u'MX优先级', blank=True, null=True)
    refresh = models.IntegerField(u'刷新时间间隔', blank=True, null=True)
    retry = models.IntegerField(u'重试时间间隔', blank=True, null=True)
    expire = models.IntegerField(u'过期时间', blank=True, null=True)
    minimum = models.IntegerField(u'最小时间', blank=True, null=True)
    serial = models.IntegerField(u'序列号', blank=True, null=True)
    resp_person = models.CharField(u'责任人', max_length=128, blank=True, null=True)
    status = models.BooleanField(u'记录状态', default=1)
    create_datetime = models.DateTimeField(u'创建时间', default=timezone.now)
    update_datetime = models.DateTimeField(u'更新时间', auto_now=True)

    class Meta:
        db_table = 'dns_records'

bind/forms.py
# -*- coding: UTF-8 -*-

from django import forms

class BindValidForm(forms.Form):
    id = forms.IntegerField(required=False)
    zone = forms.IntegerField(required=False)
    print zone
    host = forms.CharField(max_length=128, required=False)
    type = forms.CharField(max_length=128, required=False)
    data = forms.CharField(max_length=128, required=False)

bind/views.py
# -*- coding: utf-8 -*-

import sys
import json
from models import *
from forms import *
import django.utils.timezone as timezone
from django.shortcuts import render, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

'''Domain列表'''
@csrf_exempt
@login_required(login_url="/users/login/")
def DomainList(request):
    if request.method == 'GET':
        # Domain 列表
        result = DNS.objects.all()
        return render(request, 'bind/list.html', {'result': result})

'''Domain添加'''
@csrf_exempt
@login_required(login_url="/users/login/")
def DomainAdd(request):
    if request.method == 'GET':
        bind_type = DNS.dns_type_choice
        bind_zone = DNS.dns_zone_choice
        return render(request, 'bind/add.html', {'bind_type': bind_type, 'bind_zone': bind_zone})
    elif request.method == 'POST':
        dns_form = BindValidForm(request.POST)
        if dns_form.is_valid():
            zone = request.POST.get('zone')
            host = dns_form.cleaned_data['host']
            Type = dns_form.cleaned_data['type']
            data = dns_form.cleaned_data['data']
            # 添加解析
            AddObj = DNS(zone=zone, host=host, type=Type, data=data, ttl='60')
            AddObj.save()

            # 数据添加状态: true表示正常.
            return HttpResponse(json.dumps({'status': 'true'}))
        else:
            # 数据添加状态: false表示异常.
            return HttpResponse(json.dumps({'status': 'false'}))
    else:
        dns_form = BindValidForm()

'''域名删除操作'''
@csrf_exempt
@login_required(login_url="/users/login/")
def DomainDel(request):
    if request.method == 'POST':
        dns_delform = BindValidForm(request.POST)
        if dns_delform.is_valid():
            id = dns_delform.cleaned_data['id']
            DelObj = DNS.objects.filter(id=id).delete()
            # 数据添加状态: true表示正常.
            return HttpResponse(json.dumps({'status': 'true'}))
        else:
            # 数据添加状态: false表示异常.
            return HttpResponse(json.dumps({'status': 'false'}))
    else:
        dns_delform = BindValidForm()

'''域名编辑操作'''
def DomainProfile(request):
    if request.method == 'GET':
        id = request.GET['id']
        result = DNS.objects.filter(id=id).values('id', 'zone', 'host', 'type', 'data', 'ttl')
        bind_type = DNS.dns_type_choice
        bind_zone = DNS.dns_zone_choice
    return render(request, 'bind/profile.html', {'result': result, 'bind_type': bind_type, 'bind_zone': bind_zone})


'''域名更新操作'''
@csrf_exempt
def DomainUpdate(request):
    if request.method == 'POST':
        dns_upform = BindValidForm(request.POST)
        if dns_upform.is_valid():
            id = dns_upform.cleaned_data['id']
            zone = request.POST['zone']
            host = dns_upform.cleaned_data['host']
            type = dns_upform.cleaned_data['type']
            data = dns_upform.cleaned_data['data']

            # 更新域名信息
            UpdateObj = DNS.objects.filter(id=id).update(zone=zone,
                                                         host=host,
                                                         type=type,
                                                         data=data,
                                                         ttl='60',
                                                         update_datetime=timezone.now())

            # 数据更新状态: true表示正常.
            return HttpResponse(json.dumps({'status': 'true'}))
        else:
            # 数据更新状态：false表示异常.
            return HttpResponse(json.dumps({'status': 'false'}))
    else:
        dns_upform = BindValidForm()

templates/bind/add.html
{% extends "base_site.html" %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/css/dataTables.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>域名管理</h3>
        </div>
      </div>

      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>解析配置</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Settings 1</a>
                    </li>
                    <li><a href="#">Settings 2</a>
                    </li>
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <br />
              <form id="add_dnsFrom" data-parsley-validate class="form-horizontal form-label-left" action="{% url 'domain_add' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="host">主机记录 <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="host" name="host" class="form-control col-md-7 col-xs-12" placeholder="请输入主机记录">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="zone">域名记录 <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" id="zone" name="zone">
                      <!-- 域名记录 -->
                      {% for key,value in bind_zone %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">记录类型 <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" id="type" name="type">
                      <!-- 记录类型 -->
                      {% for key,value in bind_type %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="data">解析地址 <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="data" name="data" class="form-control col-md-7 col-xs-12" placeholder="请输入解析地址">
                  </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <span class="add_dnsValid">
                      <button class="btn btn-success" type="button">保存</button>
                    </span>
                    <span class="add_dnsReset">
                      <button class="btn btn-primary" type="reset">重置</button>
                    </span>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- 自定义js -->
  <script src="/static/js/validbindform.init.js"></script>
{% endblock javascripts %}

templates/bind/list.html
{% extends "base_site.html" %}

{% block stylesheets %}
  {{ block.super }}
  <link href="/static/css/dataTables.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>域名管理</h3>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>域名列表</h2>
              <ul class="nav navbar-right panel_toolbox">
			    <li><a class="collapse-link" href="{% url 'domain_add' %}"><i class="glyphicon glyphicon-plus"></i></a>
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table id="CustomDatatable" class="table table-striped table-bordered">
                <thead>
                  <tr>
                      <th>主机记录</th>
                      <th>记录类型</th>
                      <th>解析地址</th>
                      <th>TTL时间</th>
                      <th>创建时间</th>
                      <th>更新时间</th>
                      <th>操作</th>
                  </tr>
                </thead>
                <tbody>
                  {% for dns in result %}
                  <tr>
                    <td>{{ dns.host }}.{{ dns.get_zone_display }}</td>
                    <td>{{ dns.type }}</td>
                    <td>{{ dns.data }}</td>
                    <td>{{ dns.ttl }}</td>
                    <td>{{ dns.create_datetime }}</td>
                    <td>{{ dns.update_datetime }}</td>
                    <td>
                      <a class="btn btn-info btn-xs" href="{% url 'domain_profile' %}?id={{ dns.id }}">编辑</a>
                      <span class="del_dns" CurlId="{{ dns.id }}">
                        <button type="button" class="btn btn-danger btn-xs">删除</button>
                      </span>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- 自定义js -->
  <script src="/static/js/validbindform.init.js"></script>
{% endblock javascripts %}

templates/bind/profile.html
{% extends "base_site.html" %}

{% block content %}
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>域名管理</h3>
        </div>
        <div class="title_right"></div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>域名配置</h2>
              <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                  <ul class="dropdown-menu" role="menu">
                  </ul>
                </li>
                <li><a class="close-link"><i class="fa fa-close"></i></a>
                </li>
              </ul>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <br />
              {% for dns in result %}
              <form id="up_dnsForm" data-parsley-validate class="form-horizontal form-label-left" action="{% url 'domain_profile' %}?id={{ dns.id }}" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="host">主机记录 <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="host" name="host" class="form-control col-md-7 col-xs-12" value="{{ dns.host }}">
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="zone">域名记录 <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" id="zone" name="zone">
                      <!-- 域名记录 -->
                      {% for key,value in bind_zone %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="type">记录类型 <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <select class="form-control" id="type" name="type">
                      <!-- 记录类型 -->
                      {% for key,value in bind_type %}
                        <option value="{{ key }}">{{ value }}</option>
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <div class="form-group">
                  <label class="control-label col-md-3 col-sm-3 col-xs-12" for="data">解析地址 <span class="required">*</span>
                  </label>
                  <div class="col-md-6 col-sm-6 col-xs-12">
                    <input type="text" id="data" name="data" class="form-control col-md-7 col-xs-12" value="{{ dns.data }}">
                  </div>
                </div>
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <span class="up_dnsValid" CurlId="{{ dns.id }}">
                      <button type="button" class="btn btn-success">保存</button>
                    </span>
                    <span class="up_dnsReset" CurlId="{{ dns.id }}">
                      <button class="btn btn-primary" type="reset">重置</button>
                    </span>
                  </div>
                </div>
              </form>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block javascripts %}
  {{ block.super}}
  <!-- 自定义js -->
  <script src="/static/js/validbindform.init.js"></script>
{% endblock javascripts %}